env:
  node: true
  es2021: true
  es2022: true
  jest: true
reportUnusedDisableDirectives: true
parser: "vue-eslint-parser"
parserOptions:
  parser: "@typescript-eslint/parser"
  ecmaVersion: "latest"
  sourceType: "module"
root: true
plugins:
  - "@typescript-eslint"
  - vue
  - import
extends:
  - plugin:@typescript-eslint/recommended
  - "@vue/eslint-config-typescript/recommended"
  - plugin:import/recommended
  - plugin:import/typescript
settings:
  import/core-modules: [ electron ]
  import/resolver:
    typescript:
      project: 
        - ./tsconfig.json
        - apps/*/tsconfig.json

 